language: node_js
node_js:
- '6'
script:
- npm run build
before_deploy:
- cd dist
deploy:
  provider: npm
  email: WOOLAN@piratized.se
  api_key:
    secure: uBu+O49ASf/M8tBnlCGHUhsLMZsr2E9v5UPb93UoOmWN4Pxreu9ANOsg3PLkKEopbxVOn13BBcWkAH466I9WFUqlxlwLZ56fYAi14cI2OQaHnQEUlXgGHQH+BmUerW7jKMyRfMfZ4h80uqOQLovVUZtZtbrXG4ajJgKfT3nZ6I2ruRNTF2zu2GR5FicsMN+KsJ21aXnCC2FF+AGqseLr9o9rMEMlVcz76x99OJQLDVQwM+TDntvBYiketW6KLCrStFm80NNgRLsXUtsX90ldEsAXRggBMdj3NMNoCCSHALMgcfUKVwahUHI2/YE4jIT8ojTS5R3GwFacyndfwNijbFHRsgMsSAbwQEh19FQJycCAqBNLzpM0vs3ZvPvS+4TXn4gzAVVm9c/JCT4eL7yo3TiR1CR09qqT7W9Oh+0t1M7YPtRQSwlEfK0/N0QX47Uama80XVxV2731Felz9+F54lAYlzf2zFLsyUQ5YThvZH51Qr14/ApxvdTtklqQFeTwn5vFAz4POZ+tSOjQf2f+3DNK4tlur6svxhP6YY6b4FirLvhqhQVkTSyMpc5F6454PdAKHT0RrLENdnvcpvK2PtYa9BZroIZ6XepGi/mtqI7K1saXjdRqsj7FcELRayxFvjIsLhfhZUkcx136UTv0xBFoXtkLqw1EZtYqwohxq5M=
  skip_cleanup: true
  on:
    tags: true
